language: php
sudo: required
cache:
  directories:
    - $HOME/.composer/cache

# Do not build feature branch or alpha/beta releases
branches:
  only:
    - master
    - develop
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

# Inform me about failures
notifications:
  email:
    - info@arroba-it.de

# This is executed for all stages
before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

# Configure build stages (with build matrix above, test stage is implicitly defined)
jobs:
  fast_finish: true
  include:
    - &lint
      stage: test
      php: 7.2
      env: PHP Lint
      before_install: skip
      install: skip
      before_script: skip
      script:
        - errors=$(find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} 2>&1 >/dev/null \;) && echo "$errors" && test -z "$errors"
    - <<: *lint
      php: 7.1
    - <<: *lint
      php: 7.0

    - stage: test
      php: 7.1
      env: Consistency checks
      before_install: skip
      install: skip
      before_script: skip
      script:
        - >
          if [ -n "$TRAVIS_TAG" ]; then
            composer set-version $TRAVIS_TAG
            test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";
          fi
        - composer extension-create-libs && ls -la Libraries/*.phar | grep -v ^-rwx

    - stage: publish in ter
      if: tag IS present
      php: 7.0
      before_install: skip
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install requirements
            composer require --dev helhum/ter-client dev-master
            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx

            # Build extension files
            composer extension-release

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            .Build/bin/ter-client upload typo3_debugbar . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;